version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
build:
  verbosity: minimal
before_package:
- ps: Add-Content version $env:APPVEYOR_BUILD_VERSION -NoNewLine
artifacts:
- path: '\Release\*'
- path: '\version'